apiVersion: v1
kind: Service
metadata:
  name: sam-gong-server-service
  namespace: sam-gong
  labels:
    app: sam-gong-server
    app.kubernetes.io/name: sam-gong-server
    app.kubernetes.io/component: game-server
    app.kubernetes.io/managed-by: devsop
spec:
  type: ClusterIP
  selector:
    app: sam-gong-server
  ports:
    - name: ws
      port: 2567
      targetPort: 2567
      protocol: TCP
