apiVersion: v1
kind: Service
metadata:
  name: sam-gong-client-service
  namespace: sam-gong
  labels:
    app: sam-gong-client
    app.kubernetes.io/name: sam-gong-client
    app.kubernetes.io/component: frontend
    app.kubernetes.io/managed-by: devsop
spec:
  type: ClusterIP
  selector:
    app: sam-gong-client
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
